git_protocol: https
editor: nvim
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager: delta -s
aliases:
    co: '!id="$(gh pr list -S "sort:updated-desc" -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh pr checkout "$id"'
    review: '!id="$(gh pr list -L100 | fzf | cut -f1)"; [ -n "$id" ] && gh pr diff "$id"'
    oncall: issue list -R github/platform-health -S eng -l on-call -L1 --json url -q '.[].url'
    phsync: "issue list -R github/platform-health -l \"sync \U0001F504\" -L1 --json url -q '.[].url'"
    nines: "!echo Nines Issues && gh issue list -R github/platform-health-ops -s all -a @me --json title,url -t '{{range .}}{{tablerow \"-\" .url .title}}{{end}}'"
    ime: issue list -A kmcq
    il: issue list
    is: issue status
    pl: pr list
    prev: pr review
    ps: pr status
    grid: >
        !gh api graphql -f"login=$1" -F=query='query($login:String!) { user(login:$login) { id } }' | jq -r '.data.user.id' | pbcopy | echo "Copied to clipboard."

    approve: pr review --approve
    prengme: pr create -r github/platform-health-engineers -a @me
    preengme: pr edit --add-reviewer github/platform-health-engineers --add-assignee @me
    dev: '!gh cs ssh -c `gh cs create --status -r $1`'
    needreview: search prs --author @me --state open --review none
    needmyreview: search prs --review-requested=@me --state=open
    url: "!gh $([[ $@ == *\"pull\"* ]] && echo pr || echo issue) view $@ --json url -q '.url'"
    vimpr: "!nvim +\"Octo `gh pr view --json url -q '.url'`\""
    vim: "!nvim +\"Octo `gh url $@`\""
    important: "!gh search issues --repo $(project-repos) --label impact:large --state open --sort updated --order desc --no-assignee --json title,updatedAt,url -t '{{range .}}{{tablerow .title .updatedAt .url}}{{end}}'"
    dbot: "!gh search prs --repo $(project-repos) --state open --app dependabot --sort updated --order desc --json title,updatedAt,url -t '{{range .}}{{tablerow .title .updatedAt .url}}{{end}}'"
    watch: "!gh pr checks $1 --watch --required && osascript -e 'display notification \"Checks complete\" with title \"GH PR\"'"
version: "1"
