tap 'homebrew/cask-versions'
tap 'adoptopenjdk/openjdk'

brew 'ag'
brew 'coreutils'
brew 'difftastic'
brew 'gnu-tar'
brew 'go'
brew 'iproute2mac'
brew 'jesseduffield/lazygit/lazygit'
brew 'jq'
brew 'git-delta'
brew 'reattach-to-user-namespace'
brew 'ripgrep'
brew 'switchaudio-osx'
brew 'tmux'

cask "adoptopenjdk/openjdk/adoptopenjdk8" unless system "/usr/libexec/java_home --failfast --version 1.8+ &>/dev/null"

cask 'alacritty'
cask 'docker'
cask 'graphiql'
cask 'hammerspoon'
cask 'hex-fiend'
cask 'viscosity'
