#!/bin/bash

# Stashes away unstaged changes before committing so they don't get
# coopted by precommit hooks.
# Props to AP for writing this <3.

set -e

git commit --no-verify -m "temp commit - autocreated, do not push"

repo_root=$(git rev-parse --show-toplevel)
stash_force_file="${repo_root}/.force_stash_${RANDOM}"
touch "${stash_force_file}"
git stash push --include-untracked -m "Autocreated before commit"

git reset --soft HEAD~

set +e
git commit "$@"
commit_exit_code=$?

git stash pop -q
stash_exit_code=$?

rm "${stash_force_file}"

if [ $commit_exit_code -ne 0 ]; then
  exit $commit_exit_code
else
  exit $stash_exit_code
fi
